// TurboQuant3 TCQ CUDA flash attention vec kernel instantiation

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE_NO_SOFTCAP(128, GGML_TYPE_TURBO3_TCQ, GGML_TYPE_TURBO3_TCQ);
DECL_FATTN_VEC_CASE_NO_SOFTCAP(256, GGML_TYPE_TURBO3_TCQ, GGML_TYPE_TURBO3_TCQ);
