// TurboQuant3 CUDA flash attention vec kernel instantiation

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE_NO_SOFTCAP( 64, GGML_TYPE_TURBO3_0, GGML_TYPE_TURBO3_0);
DECL_FATTN_VEC_CASE_NO_SOFTCAP(128, GGML_TYPE_TURBO3_0, GGML_TYPE_TURBO3_0);
DECL_FATTN_VEC_CASE_NO_SOFTCAP(256, GGML_TYPE_TURBO3_0, GGML_TYPE_TURBO3_0);
DECL_FATTN_VEC_CASE_NO_SOFTCAP(512, GGML_TYPE_TURBO3_0, GGML_TYPE_TURBO3_0);
